### ISSUE TITLE
Error in PETSc build

### ISSUE THREAD

**Issue by mattia-** [hashdist/hashdist#305]
I get an error when trying to build PETSc. The PETSc build is performed as part of a FEniCS build, so the profile file I'm using is this one https://bitbucket.org/fenics-project/fenics-developer-tools/src/37da88a3ce92c682ad720527afaa528c1498611a/install/profiles/fenics.Linux.yaml?at=master.
The error I get is: 
```
>$ tail -f /home/usr/local/hashdist_software/tmp/petsc-yy2u262ua6c7/build.log
2015/02/06 15:07:53 - INFO: [package:run_job] TESTING: configureAutoreconf from config.programs(/home/usr/local/hashdist_software/tmp/petsc-yy2u262ua6c7/config/BuildSystem/config/programs.py:44)
2015/02/06 15:07:53 - INFO: [package:run_job] *******************************************************************************
2015/02/06 15:07:53 - INFO: [package:run_job]                     UNABLE to EXECUTE BINARIES for ./configure 
2015/02/06 15:07:53 - INFO: [package:run_job] -------------------------------------------------------------------------------
2015/02/06 15:07:53 - INFO: [package:run_job] [Errno 39] Directory not empty: '/home/usr/local/hashdist_software/tmp/petsc-yy2u262ua6c7/_tmp/petsc-goazcC/config.programs/autoconfdir/autom4te.cache'
2015/02/06 15:07:53 - INFO: [package:run_job] *******************************************************************************
2015/02/06 15:07:53 - INFO: [package:run_job] 
2015/02/06 15:07:53 - ERROR: [package:run_job] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 1
2015/02/06 15:07:53 - ERROR: [package:run_job] command failed (code=1); raising
```
Checking what is inside that folder I get:
```
>$ ls -a /home/usr/local/hashdist_software/tmp/petsc-yy2u262ua6c7/_tmp/petsc-goazcC/config.programs/autoconfdir/autom4te.cache
.  ..  .nfs000000000f6e034600000107
```
Apparently, some kind of lock file is left in there preventing the build to go on.

Is this just me? What can I do?

**Comment by certik** [comment]
HI @mattia-, that's a network file system (NFS) handle, that usually takes a little longer to disappear.

The actual problem is why PETSc requires this directory to be empty. I don't know if this is a PETSc bug or a Hashdist bug.

**Comment by mattia-** [comment]
Hi @certik, thanks for the quick reply!
As a matter of fact, I *am* trying to build FEniCS on a disk common to all the computers in my university cluster mounted with NFS. Silly of me not to think of it, considering the name of the lock file. 
I will try and switch to a local tmp folder in ~/.hashdist/config.yaml and see what happens.

**Comment by certik** [comment]
If you go to your `.hashdist/config.yaml`, you can configure where to put `tmp`. For example, here is mine:
```
build_stores:
 - dir: /local/certik/bld
build_temp: /local/certik/tmp
source_caches:
 - dir: /local/certik/src
cache: /local/certik/cache
gc_roots: /local/certik/gcroots
```
As you can see, I moved everything off NFS. But you can just keep the `bld` on NFS, so that you can access it from other computers, and keep the rest off NFS.

**Comment by mattia-** [comment]
Yes, that is exactly what I did. I left my build directory on the NFS disk and moved the tmp directory. That solved my problem. Evidently the delay in the release of lock files on NFS disks that you mentioned was exactly what caused the error. 
I believe there is no way to solve this except from moving the tmp directory like you suggested, so, if it's ok with you, I think I can close this.
Thank you very much for your help!!

**Comment by certik** [comment]
I think it's fine, we can close it now. It's probably a PETSc build system bug, but since you have a workaround now, I am closing it.

**Comment by mattia-** [comment]
Ok, thank you very much again!!

**Comment by ahmadia** [comment]
@mattia- Thanks for reporting, @certik - You're awesome!
