### ISSUE TITLE
Building GDB on Ubuntu 14.04 returns no module named lzma

### ISSUE THREAD

**Issue by chvillanuevap** [hashdist/hashdist#316]
When I try to build the gdb debugger on Ubuntu 14.04, using the gdb.yaml profile, I get the following error:

Downloading https://ftp.gnu.org/gnu/gdb/gdb-7.9.tar.xz...
[=========================] 100.0% (17.0MB of 17.0MB) 0.979MB/s ETA 0s  0s  
[CRITICAL] Uncaught exception:
[CRITICAL] Traceback (most recent call last):
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/cli/main.py", line 202, in help_on_exceptions
[CRITICAL]     return func(*args, **kw)
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/cli/main.py", line 174, in command_line_entry_point
[CRITICAL]     retcode = args.subcommand_handler(ctx, args)
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/cli/frontend_cli.py", line 51, in run
[CRITICAL]     self.profile_builder_action()
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/cli/frontend_cli.py", line 108, in profile_builder_action
[CRITICAL]     self.args.k, self.args.debug)
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/spec/builder.py", line 147, in build
[CRITICAL]     self._package_specs[pkgname].fetch_sources(self.source_cache)
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/spec/package.py", line 61, in fetch_sources
[CRITICAL]     source_cache.fetch(source_clause['url'], source_clause['key'], self.name)
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/core/decorators.py", line 71, in f_retry
[CRITICAL]     return f(*args, **kwargs)
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/core/source_cache.py", line 345, in fetch
[CRITICAL]     handler.fetch(url, type, hash, repo_name)
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/core/source_cache.py", line 757, in fetch
[CRITICAL]     self.fetch_archive(url, type, hash)
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/core/source_cache.py", line 766, in fetch_archive
[CRITICAL]     return self._download_archive(url, type, expected_hash)
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/core/source_cache.py", line 770, in _download_archive
[CRITICAL]     temp_file, hash = self._download_and_hash(url, type)
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/core/source_cache.py", line 722, in _download_and_hash
[CRITICAL]     if not create_archive_handler(type, self.logger).verify(temp_path):
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/core/source_cache.py", line 856, in verify
[CRITICAL]     with closing(self.tarfileobj_from_name(filename)) as tarfileobj:
[CRITICAL]   File "/tmp/fenics-install.fU4s6o/hashdist/hashdist/core/source_cache.py", line 923, in tarfileobj_from_name
[CRITICAL]     import lzma
[CRITICAL] ImportError: No module named lzma
[CRITICAL] This exception has not been translated to a human-friendly error message,
[CRITICAL] please file an issue at https://github.com/hashdist/hashdist/issues pasting
[CRITICAL] this stack trace.

I saw the note on the gdb.yaml file about the issues with OSX. Do I need to install LZMA separately?

**Comment by certik** [comment]
You need to make sure that the Python that is used to execute `hit` contains the lzma module. That's because the gdb is using the xz format.

What I do is that I first install Python + lzma, and then use it to install the rest of Hashstack.

**Comment by chvillanuevap** [comment]
Python + lzma would be installed independently of my HashDist profile using apt-get in Ubuntu?

Or can I set it up as part of the profile?

**Comment by certik** [comment]
It needs to be installed independently. However, you can install it (independently) using Hashdist --- just install it into a profile and add the profile/bin into your path. Then run hit (thus using the Python from this profile) to build gdb.

You can also just install lzma into your Ubuntu --- but that only works if you have a root access to your computer, which typically you don't have on clusters.
