### ISSUE TITLE
HashDist vs Conda vs Buildout vs pip

### ISSUE THREAD

**Issue by chvillanuevap** [hashdist/hashdist#321]
I think a comparison, or at least a brief description of the differences between these packages might be useful to include in the documentation.

I understand the differences between Conda and pip for example, and a good description is found here:

http://stackoverflow.com/questions/20994716/what-is-the-difference-between-pip-and-conda

However, I still do not understand why HashDist is needed over Conda, or what different problem it solves. Is is about root privileges? Building from source?

Understanding why HashDist is better than Conda or pip for some scenarios would prove useful in getting more people to use HashDist.

**Comment by certik** [comment]
+1

**Comment by chvillanuevap** [comment]
I found these references:

https://packaging.python.org/en/latest/projects.html#conda
https://packaging.python.org/en/latest/projects.html#hashdist

But it is still not clear to me on which scenarios I would use HashDist over Conda.

**Comment by certik** [comment]
cc @cekees, @ahmadia

**Comment by ahmadia** [comment]
To be succinct, HashDist provides and uses functional software build specifications that enables installation and distribution.  Conda is a binary installation and distribution tool that enables community-supported recipes.

HashDist focuses more on specifying and building software, conda is more focused on distribution and installation.
