### ISSUE TITLE
Cannot build MPICH on Ubuntu 14.04

### ISSUE THREAD

**Issue by chvillanuevap** [hashdist/hashdist#324]
I am trying to build the MPI package using MPICH.

```
packages:
  mpi:
    use: mpich
```

I get the following error:

```
2015/04/19 14:34:12 - INFO: [package:run_job] configure: ===== done with src/openpa configure =====
2015/04/19 14:34:12 - INFO: [package:run_job] sourcing /home/villanueva/.hashdist/tmp/mpi-gmkx3ftk3tz2/src/pm/hydra/mpichprereq
2015/04/19 14:34:12 - INFO: [package:run_job] checking whether the compiler defines __func__... yes
2015/04/19 14:34:13 - INFO: [package:run_job] checking whether the compiler defines __FUNC__... no
2015/04/19 14:34:13 - INFO: [package:run_job] checking whether the compiler sets __FUNCTION__... yes
2015/04/19 14:34:13 - INFO: [package:run_job] checking whether C compiler accepts option -O2... yes
2015/04/19 14:34:13 - INFO: [package:run_job] checking whether C compiler option -O2 works with an invalid prototype program... yes
2015/04/19 14:34:13 - INFO: [package:run_job] checking whether routines compiled with -O2 can be linked with ones compiled without -O2... yes
2015/04/19 14:34:13 - INFO: [package:run_job] checking for type of weak symbol alias support... pragma weak
2015/04/19 14:34:13 - INFO: [package:run_job] checking whether __attribute__ ((weak)) allowed... yes
2015/04/19 14:34:13 - INFO: [package:run_job] checking whether __attribute__ ((weak_import)) allowed... yes
2015/04/19 14:34:14 - INFO: [package:run_job] checking whether __attribute__((weak,alias(...))) allowed... no
2015/04/19 14:34:14 - INFO: [package:run_job] checking for multiple weak symbol support... yes
2015/04/19 14:34:14 - INFO: [package:run_job] checking for shared library (esp. rpath) characteristics of CC... done (results in src/env/cc_shlib.conf)
2015/04/19 14:34:14 - INFO: [package:run_job] checking whether Fortran 77 compiler accepts option -O2... no
2015/04/19 14:34:14 - INFO: [package:run_job] checking how to get verbose linking output from fort77... -v
2015/04/19 14:34:14 - INFO: [package:run_job] checking for Fortran 77 libraries of fort77...  -L/home/villanueva/.hashdist/bld/libxml2/mlk7x2dhjiud/lib -L/home/villanueva/.hashdist/bld/patchelf/k3rloj265ogt/lib -L/home/villanueva/.hashdist/bld/pkg-config/pjksilnbb4iy/lib -lf2c -lm
2015/04/19 14:34:14 - INFO: [package:run_job] checking whether fort77 accepts the FLIBS found by autoconf... no
2015/04/19 14:34:14 - INFO: [package:run_job] checking for valid entries in FLIBS...
2015/04/19 14:34:14 - INFO: [package:run_job] checking whether gcc links with FLIBS found by autoconf... yes
2015/04/19 14:34:15 - INFO: [package:run_job] checking whether Fortran 77 and C objects are compatible... no
2015/04/19 14:34:15 - INFO: [package:run_job] checking for file... file
2015/04/19 14:34:15 - INFO: [package:run_job] configure: error: Could not determine a way to link a Fortran test program!
2015/04/19 14:34:15 - INFO: [package:run_job] checking for linker for Fortran main program...
2015/04/19 14:34:15 - ERROR: [package:run_job] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 1
2015/04/19 14:34:15 - ERROR: [package:run_job] command failed (code=1); raising
```

Notice the `INFO: [package:run_job] configure: error: Could not determine a way to link a Fortran test program!` error.

This is the MPICH package configuration:

```
  # MPICH version 3.0.3.
  mpich:
    sources:
    - key: tar.gz:jj5yo7oe3e45wwngkuqqn35bud5kdfkr
      url: http://www.mpich.org/static/tarballs/3.0.3/mpich-3.0.3.tar.gz
    build_stages:
      - name: configure
        mode: update
        extra: ['--disable-f77', '--disable-fc']
```

I do not understand the error because I have f77 disabled. Has anyone encountered this issue?

**Comment by johannesring** [comment]
The following might work as you would expect:

    mpi:
      use: mpich
      sources:
      - key: tar.gz:jj5yo7oe3e45wwngkuqqn35bud5kdfkr
        url: http://www.mpich.org/static/tarballs/3.0.3/mpich-3.0.3.tar.gz
      build_stages:
       - name: configure
         mode: update
         extra: ['--disable-f77', '--disable-fc']

However, the correct way would be to set the `fortran` parameter to `false`. It is set to `true` by default in `linux.yaml`. For instance, the following profile should do the trick:

    extends:
     - file: linux.yaml
    
    parameters:
      fortran: false

    packages:
      mpi:
        use: mpich
        sources:
        - key: tar.gz:jj5yo7oe3e45wwngkuqqn35bud5kdfkr
          url: http://www.mpich.org/static/tarballs/3.0.3/mpich-3.0.3.tar.gz

**Comment by chvillanuevap** [comment]
Thank you very much! I see this is somewhat related to issue #323, as the user should not add the MPI package (OpenMPI, MPICH, etc.) explicitly, but rather just inside the `mpi` package configuration.

**Comment by chvillanuevap** [comment]
If I set `fortran: false` as a global parameter, will it turn off fortran for all packages as well? For example, the `gcc` package will no longer build `gfortran`?

**Comment by certik** [comment]
According to this line https://github.com/hashdist/hashstack/blob/43e5c252fd4b8843570572ebcb68ac1437de8016/pkgs/gcc/gcc.py#L39, gcc will always build gfortran.

**Comment by chvillanuevap** [comment]
I see, thanks!

On that note, where does the GCC package set the environment variables `CC`, `CXX`, etc.?

**Comment by certik** [comment]
@chvillanuevap I don't think the gcc package sets `CC`, `CXX` at all. What leads you to believe that those are set?

**Comment by chvillanuevap** [comment]
If I include the gcc package as part of my profile, I want the other packages to be built with this gcc, not the host gcc. This is more related to my issue #323. Is this possible?

**Comment by certik** [comment]
Yes it is. See here: https://gist.github.com/certik/db990b8260e77830fa48, install the `hd_base`, then use it from the test profile. Please let me know if it works for you. We should add this into our examples (feel free to submit a PR).

**Comment by chvillanuevap** [comment]
So this is the key piece, right?

```
parameters:
  PROLOGUE: |
    export PATH="/local/certik/bld/profile/bto56eplrk4v/bin:$PATH"; export CC=gcc CXX=g++ FC=gfortran
```

My confusion arose from the fact that MPICH and OpenMPI do set MPICC and MPICXX, while gcc does not.

**Comment by certik** [comment]
That's because packages must explicitly depend on `mpi`, but we do not currently depend on compilers directly, because with compilers you run into a chicken and an egg problem ---- the compilers depend on quite a few non-trivial packages to build, but then you need to rebuild these packages again with the new compiler. Thus the only way is to build compilers in one profile, and then use this profile in PROLOGUE to build the other profile. @chvillanuevap if you know any other way how this could work, please let us know.

cc @ahmadia, @cekees

**Comment by chvillanuevap** [comment]
Thanks for clarifying. That makes a lot of sense.

I will use your HashDist bootstrap to set up my profile.
