### ISSUE TITLE
keep build folder, sources and object files for possible debugging

### ISSUE THREAD

**Issue by davydden** [hashdist/hashdist#356]
would be nice to keep it in case one needs to debug third-party-libraries. Essentialy, do not delete build folders from `/tmp`.

There is an unmerged PR https://github.com/hashdist/hashdist/pull/345 which could provide a work-around, but it would be more complicated.

**Comment by johannesring** [comment]
You can keep the build directory using `hit build -k always`. For debugging, try `hit build --debug`.

**Comment by davydden** [comment]
so if I do `hit build -k` it will keep all building directories for packages?

**Comment by davydden** [comment]
seems to be working, thanks a lot!

for a reference:
```
  -k KEEP_BUILD      keep build directory: always, never, error (default:
                     error)
```
