### ISSUE TITLE
Force to rebuild everything, ignoring installed packages

### ISSUE THREAD

**Issue by dajuno** [hashdist/hashdist#359]
Hi, 
is it possible to tell hit to build everything new and to ignore the installed packages?

I updated gcc 5.2.0 -> 5.3.0 and need to recompile a project (fenics). I did `hit mv` + `hit build`. The new build references packages that were built before (namely mpi when compiling boost), which fails with
`error 'Please use the same version of GCC and g++ for compiling MPICH and user MPI programs'`.
So I need to enforce rebuilding of *all* the packages. 

I guess it would work if I just threw away the old build, but until I know the new one works I don't want to do that.

Thanks

**Comment by johannesring** [comment]
There may be other ways to do this, but one way is to copy your old `.yaml` profile and add something to the `PROLOGUE`:

    parameters:
      PROLOGUE: |
        echo "something"

All packages will be rebuilt, while the old build will still be available.

**Comment by dajuno** [comment]
Ok, thanks for the answer!
