### ISSUE TITLE
ConstructorError: while constructing a mapping

### ISSUE THREAD

**Issue by charlesxwang** [hashdist/hashdist#371]
Hi, friends, 
I have an issue while running a script on Mac.
The script can be found here:
**https://bitbucket.org/fenics-project/fenics-developer-tools/src/3a353bd7f41142e165769fafb198afedef64c59b/install/fenics-install-all.sh?at=master&fileviewer=file-view-default**

Anybody can give a hint? Thanks!

**The following is the log:**

Using HashDist profile /private/tmp/fenics-install.SVVnzy/fenics-developer-tools/install/profiles/fenics-deps.Darwin.yaml.

Building dependencies only.

Starting build...

[CRITICAL] Uncaught exception:
[CRITICAL] Traceback (most recent call last):
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/cli/main.py", line 202, in help_on_exceptions
[CRITICAL]     return func(*args, **kw)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/cli/main.py", line 174, in command_line_entry_point
[CRITICAL]     retcode = args.subcommand_handler(ctx, args)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/cli/frontend_cli.py", line 51, in run
[CRITICAL]     self = cls(ctx, args)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/cli/frontend_cli.py", line 46, in __init__
[CRITICAL]     self.profile = load_profile(self.ctx.logger, self.checkouts, args.profile, parameters)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/spec/profile.py", line 539, in load_profile
[CRITICAL]     doc = load_and_inherit_profile(checkout_manager, profile_file, None, override_parameters)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/spec/profile.py", line 484, in load_and_inherit_profile
[CRITICAL]     doc = load_yaml_from_file(checkouts.resolve(profile_file))
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/formats/marked_yaml.py", line 198, in load_yaml_from_file
[CRITICAL]     return marked_yaml_load(expanded_stream, filecaption)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/formats/marked_yaml.py", line 189, in marked_yaml_load
[CRITICAL]     return MarkedLoader(stream, filecaption).get_single_data()
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/deps/yaml/constructor.py", line 39, in get_single_data
[CRITICAL]     return self.construct_document(node)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/deps/yaml/constructor.py", line 43, in construct_document
[CRITICAL]     data = self.construct_object(node)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/deps/yaml/constructor.py", line 88, in construct_object
[CRITICAL]     data = constructor(self, node)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/formats/marked_yaml.py", line 139, in construct_yaml_map
[CRITICAL]     obj, = SafeConstructor.construct_yaml_map(self, node)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/deps/yaml/constructor.py", line 401, in construct_yaml_map
[CRITICAL]     value = self.construct_mapping(node)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/deps/yaml/constructor.py", line 211, in construct_mapping
[CRITICAL]     return BaseConstructor.construct_mapping(self, node, deep=deep)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/deps/yaml/constructor.py", line 133, in construct_mapping
[CRITICAL]     value = self.construct_object(value_node, deep=deep)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/deps/yaml/constructor.py", line 88, in construct_object
[CRITICAL]     data = constructor(self, node)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/formats/marked_yaml.py", line 139, in construct_yaml_map
[CRITICAL]     obj, = SafeConstructor.construct_yaml_map(self, node)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/deps/yaml/constructor.py", line 401, in construct_yaml_map
[CRITICAL]     value = self.construct_mapping(node)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/deps/yaml/constructor.py", line 211, in construct_mapping
[CRITICAL]     return BaseConstructor.construct_mapping(self, node, deep=deep)
[CRITICAL]   File "/private/tmp/fenics-install.SVVnzy/hashdist/hashdist/deps/yaml/constructor.py", line 136, in construct_mapping
[CRITICAL]     "found already in-use key (%s)" % key, key_node.start_mark)
[CRITICAL] ConstructorError: while constructing a mapping
[CRITICAL]   in "/private/tmp/fenics-install.SVVnzy/hashstack/default.yaml", line 23, column 3
[CRITICAL] found already in-use key (parmetis)
[CRITICAL]   in "/private/tmp/fenics-install.SVVnzy/hashstack/default.yaml", line 57, column 3
[CRITICAL] This exception has not been translated to a human-friendly error message,
[CRITICAL] please file an issue at https://github.com/hashdist/hashdist/issues pasting
[CRITICAL] this stack trace.

**Comment by johannesring** [comment]
This was a bug in https://bitbucket.org/fenics-project/fenics-developer-tools, not in hashdist. I have fixed the problem now.
